baseURL: "https://qinyu.github.io"
languageCode: zh-cn
title: 覃宇｜Qin Yu is writing
theme: 
  - anatole
taxonomies:
  category: categories
  series: series
  tag: tags
mainSections:
  - post
defaultContentLanguage: zh-cn
ignoreFiles:
  - content/temp/
markup:
  highlight:
    style: solarized-light
    noClasses: false
    codeFences: true
    guessSyntax: true
