main:
  - name: 最近更新
    weight: 100
    identifier: home
    url: /
  - name: 翻译作品
    weight: 200
    identifier: translations
    url: /translations/
  - name: 出版物
    weight: 300
    identifier: books
    url: /books/
  - name: 归档
    weight: 400
    identifier: posts
    url: /post/
  - name: 关于
    weight: 500
    identifier: about
    url: /about/
