title: 覃宇码字的地方
author: 覃宇
contentratio: 0.7
favicon: "favicons/"
description: |
  前Thoughtworker
  移动应用架构师
  技术教练
profilePicture: images/profile.jpg
customCss:
  - css/custom.css
customJs:
  - js/parallax.js
googleAnalytics: false
displayMode: dark
disableThemeSwitcher: true
disableTitleCapitalization: true
indexDateFormat: "2006-01-02"
singleDateFormat: "2006-01-02"
listDateFormat: "2006-01-02"
socialIcons:
  - icon: fab fa-github
    title: GitHub
    url: https://github.com/qinyu/
  - icon: fab fa-x-twitter
    title: X
    url: https://x.com/qinyu
  - icon: fab fa-weixin
    title: 微信公众号：覃宇码字的地方
    url: /wechat/
  - icon: fas fa-envelope
    title: e-mail
    url: 'mailto:qinyusuain@gmail.com'
