baseURL = 'https://qinyu.github.io'
languageCode = 'zh-cn'
title = "qinyu's site"
theme = 'anatole'

[params]
title = "覃宇"
author = "qinyu"
description = "Thoughtworker\n移动应用架构师\n技术教练"
profilePicture = "images/profile.jpg"
mainSections = ["关于"]

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/qinyu/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:qinyusuain@gmail.com"

[[menus.main]]
name = "文章"
weight = 200
identifier = "posts"
url = "/post/"

[[menus.main]]
name = "成就"
weight = 300
identifier = "accomplishments"

[[menus.main]]
name = "出版物"
weight = 310
identifier = "books"
url = "/books/"
parent = "accomplishments"  

[[menus.main]]
name = "线上课"
weight = 320
identifier = "courses"
url = "/courses/"
parent = "accomplishments"

[[menus.main]]
name = "关于"
weight = 400
identifier = "about"
url = "/about/"